/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.AdminController;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.AdminModel;

/**
 *
 * @author MELON
 */
public class Admin extends javax.swing.JFrame {
      private AdminController admincontroller;
      private AdminModel adminmodel;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        admincontroller = new AdminController (this);
      admincontroller.isiTablePekerja();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        next2 = new javax.swing.JLabel();
        next3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpekerja = new javax.swing.JTable();
        Userbisnis = new javax.swing.JLabel();
        next5 = new javax.swing.JLabel();
        next6 = new javax.swing.JLabel();
        next7 = new javax.swing.JLabel();
        next4 = new javax.swing.JLabel();
        next9 = new javax.swing.JLabel();
        next10 = new javax.swing.JLabel();
        next11 = new javax.swing.JLabel();
        next12 = new javax.swing.JLabel();
        Hapus = new javax.swing.JButton();
        next13 = new javax.swing.JLabel();
        next14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_user = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(24, 32, 38));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        next2.setBackground(new java.awt.Color(24, 32, 38));
        next2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next2.setForeground(new java.awt.Color(255, 255, 255));
        next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-logout-rounded-left-25.png"))); // NOI18N
        next2.setText("Logout");
        next2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(next2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(next2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 40));

        next3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next3.setForeground(new java.awt.Color(255, 255, 255));
        next3.setText("Pekerja");
        getContentPane().add(next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, 30));

        jpekerja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jpekerja.setRowHeight(30);
        jpekerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpekerjaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jpekerja);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1050, 250));

        Userbisnis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Userbisnis.setForeground(new java.awt.Color(255, 255, 255));
        Userbisnis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-company-100_1.png"))); // NOI18N
        Userbisnis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserbisnisMouseClicked(evt);
            }
        });
        getContentPane().add(Userbisnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 120, 150));

        next5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next5.setForeground(new java.awt.Color(255, 255, 255));
        next5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-form-100.png"))); // NOI18N
        next5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next5MouseClicked(evt);
            }
        });
        getContentPane().add(next5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 110, 150));

        next6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next6.setForeground(new java.awt.Color(255, 255, 255));
        next6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-user-male-128.png"))); // NOI18N
        getContentPane().add(next6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 150));

        next7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next7.setForeground(new java.awt.Color(255, 255, 255));
        next7.setText("Postingan");
        getContentPane().add(next7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 90, 30));

        next4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next4.setForeground(new java.awt.Color(255, 255, 255));
        next4.setText("Admin");
        getContentPane().add(next4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 40));

        next9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next9.setForeground(new java.awt.Color(255, 255, 255));
        next9.setText("Bisnis");
        getContentPane().add(next9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 80, 30));

        next10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next10.setForeground(new java.awt.Color(255, 255, 255));
        next10.setText("Daftar User Pekerja");
        getContentPane().add(next10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        next11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next11.setForeground(new java.awt.Color(255, 255, 255));
        next11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-permanent-job-100.png"))); // NOI18N
        next11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next11MouseClicked(evt);
            }
        });
        getContentPane().add(next11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 140, 150));

        next12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next12.setForeground(new java.awt.Color(255, 255, 255));
        next12.setText("Pekerjaan Aktif");
        getContentPane().add(next12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 160, 30));

        Hapus.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/trash.png"))); // NOI18N
        Hapus.setText("Hapus");
        Hapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 100, -1));

        next13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next13.setForeground(new java.awt.Color(255, 255, 255));
        next13.setText("Catatan Pekerja");
        getContentPane().add(next13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 160, 30));

        next14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next14.setForeground(new java.awt.Color(255, 255, 255));
        next14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/pencil.png"))); // NOI18N
        next14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next14MouseClicked(evt);
            }
        });
        getContentPane().add(next14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 140, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tentang new.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        id_user.setText("jTextField1");
        getContentPane().add(id_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserbisnisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserbisnisMouseClicked
     new Admin_bisnis().show();
        this.dispose(); 
    }//GEN-LAST:event_UserbisnisMouseClicked

    private void next5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next5MouseClicked
    new Admin_posting().show();
        this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_next5MouseClicked

    private void next11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next11MouseClicked
      new Admin_Paktif().show();
        this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_next11MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        admincontroller.DataUser(Integer.parseInt(id_user.getText()));
        boolean hasil = admincontroller.deleteUser();
        if (hasil){
            JOptionPane.showMessageDialog(null, "User Berhasill Dihapus");
            Admin home = new Admin(); 
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "User Gagal Dihapus");
        }// TODO add your handling code here:
    }//GEN-LAST:event_HapusActionPerformed

    private void jpekerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpekerjaMouseClicked
admincontroller.isiField(jpekerja.getSelectedRow());     
// TODO add your handling code here:
    }//GEN-LAST:event_jpekerjaMouseClicked

    private void next14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next14MouseClicked
      new Admin_catatan().show();
        this.dispose(); 
    }//GEN-LAST:event_next14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JLabel Userbisnis;
    private javax.swing.JTextField id_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jpekerja;
    private javax.swing.JLabel next10;
    private javax.swing.JLabel next11;
    private javax.swing.JLabel next12;
    private javax.swing.JLabel next13;
    private javax.swing.JLabel next14;
    private javax.swing.JLabel next2;
    private javax.swing.JLabel next3;
    private javax.swing.JLabel next4;
    private javax.swing.JLabel next5;
    private javax.swing.JLabel next6;
    private javax.swing.JLabel next7;
    private javax.swing.JLabel next9;
    // End of variables declaration//GEN-END:variables

 public JTextField getTxtiduser(){
        return id_user;
    }
 public JTable getTabelPekerja() {
        return jpekerja;
    }

 

}
