/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.UserController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.UserModel;

/**
 *
 * @author MELON
 */
public class EditAkunUser extends javax.swing.JFrame {
private UserController usercontroller;
private UserModel usermodel;
    /**
     * Creates new form EditAkunUser
     */
    public EditAkunUser() {
        initComponents();
        usercontroller = new UserController (this);
        tnama.setText(UserModel.getUsernameUser());
        tpas.setText(UserModel.getPasswordUser());
        temail.setText(UserModel.getEmailUser());
        ttelpon.setText(UserModel.getNohpUser());
        tkeahlian.setText(UserModel.getKeahlianUser());

int ja = UserModel.getLevelUser();
if (ja == 1){
    RdPekerja.setSelected(true);
}else {
    RdPerusahaan.setSelected(true);
}

        
         member.setText("Selamat Datang " + UserModel.getUsernameUser()+ " (Pekerja) ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        temail = new javax.swing.JTextField();
        tpas = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        ttelpon = new javax.swing.JTextField();
        tkeahlian = new javax.swing.JTextField();
        next3 = new javax.swing.JLabel();
        next5 = new javax.swing.JLabel();
        next6 = new javax.swing.JLabel();
        next7 = new javax.swing.JLabel();
        next8 = new javax.swing.JLabel();
        next9 = new javax.swing.JLabel();
        member = new javax.swing.JLabel();
        Simpan = new javax.swing.JButton();
        RdPekerja = new javax.swing.JRadioButton();
        RdPerusahaan = new javax.swing.JRadioButton();
        next11 = new javax.swing.JLabel();
        next12 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        next2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        next10 = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();
        KlikTemukan = new javax.swing.JLabel();
        KlikListP = new javax.swing.JLabel();
        KlikCatatan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        temail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 380, 30));

        tpas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 43, 54)));
        getContentPane().add(tpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 380, 30));

        tnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 32, 38), 2));
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 380, 30));

        ttelpon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ttelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 380, 30));

        tkeahlian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tkeahlian, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 380, 30));

        next3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next3.setForeground(new java.awt.Color(255, 255, 255));
        next3.setText("Edit Akun");
        getContentPane().add(next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 150, 30));

        next5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next5.setForeground(new java.awt.Color(255, 255, 255));
        next5.setText("Username         :");
        getContentPane().add(next5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 150, 30));

        next6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next6.setForeground(new java.awt.Color(255, 255, 255));
        next6.setText("Password          :");
        getContentPane().add(next6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 150, 30));

        next7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next7.setForeground(new java.awt.Color(255, 255, 255));
        next7.setText("Email                :");
        getContentPane().add(next7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 150, 30));

        next8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next8.setForeground(new java.awt.Color(255, 255, 255));
        next8.setText("No Hp             :");
        getContentPane().add(next8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 150, 30));

        next9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next9.setForeground(new java.awt.Color(255, 255, 255));
        next9.setText("Keahlian         :");
        getContentPane().add(next9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 150, 30));

        member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("Nama Login");
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 320, 50));

        Simpan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Simpan.setText("Simpan Perubahan");
        Simpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 150, 60));

        RdPekerja.setForeground(new java.awt.Color(255, 255, 255));
        RdPekerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdPekerjaActionPerformed(evt);
            }
        });
        getContentPane().add(RdPekerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, -1, -1));

        RdPerusahaan.setForeground(new java.awt.Color(255, 255, 255));
        RdPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdPerusahaanActionPerformed(evt);
            }
        });
        getContentPane().add(RdPerusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 530, 20, 20));

        next11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next11.setForeground(new java.awt.Color(255, 255, 255));
        next11.setText("Pekerja");
        getContentPane().add(next11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 110, 40));

        next12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next12.setForeground(new java.awt.Color(255, 255, 255));
        next12.setText("Bisnis");
        getContentPane().add(next12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 90, 40));

        jPanel11.setBackground(new java.awt.Color(24, 32, 38));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        next2.setBackground(new java.awt.Color(24, 32, 38));
        next2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next2.setForeground(new java.awt.Color(255, 255, 255));
        next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-logout-rounded-left-25.png"))); // NOI18N
        next2.setText("Logut");
        next2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(next2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(next2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 620, 90, 40));

        jPanel1.setBackground(new java.awt.Color(24, 43, 54));

        next10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next10.setForeground(new java.awt.Color(255, 255, 255));
        next10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-user-male-128.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(next10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(next10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HDUser.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        KlikTemukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikTemukanMouseClicked(evt);
            }
        });
        getContentPane().add(KlikTemukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, 30));

        KlikListP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikListPMouseClicked(evt);
            }
        });
        getContentPane().add(KlikListP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 30));

        KlikCatatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikCatatanMouseClicked(evt);
            }
        });
        getContentPane().add(KlikCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KlikTemukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikTemukanMouseClicked
        new Temukan().show();
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_KlikTemukanMouseClicked

    private void KlikListPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikListPMouseClicked
        new ListPekerjaan().show();
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_KlikListPMouseClicked

    private void KlikCatatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikCatatanMouseClicked
        new Catatan().show();
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_KlikCatatanMouseClicked

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed

         int level = 0;
    if (RdPekerja.isSelected() == true ){
    level = 1 ;
    }else if (RdPerusahaan.isSelected() == true ){
        level = 2 ;
    }
   
    if (level == 0){
    JOptionPane.showMessageDialog(null, "Pilih akun gan");
    

    }
        else{
        
        


        
        
   usercontroller.DataUser(tnama.getText(), tpas.getText(), temail.getText(), ttelpon.getText(), tkeahlian.getText(),level);

     boolean hasil = usercontroller.UpdateUserr();
   
   
      if (hasil){
    JOptionPane.showMessageDialog(null, "Data Berhasill Diubah Silahkan Login Kembali");
                Login home = new Login();
    home.setVisible(true);
    this.dispose();
    }else {
    JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
    EditAkunUser home = new EditAkunUser();
    home.setVisible(true);
    this.dispose();
    }
    }    // TODO add your handling code here:
    }//GEN-LAST:event_SimpanActionPerformed

    private void RdPekerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdPekerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdPekerjaActionPerformed

    private void RdPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdPerusahaanActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAkunUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAkunUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAkunUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAkunUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAkunUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel KlikCatatan;
    private javax.swing.JLabel KlikListP;
    private javax.swing.JLabel KlikTemukan;
    private javax.swing.JRadioButton RdPekerja;
    private javax.swing.JRadioButton RdPerusahaan;
    private javax.swing.JButton Simpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel member;
    private javax.swing.JLabel next10;
    private javax.swing.JLabel next11;
    private javax.swing.JLabel next12;
    private javax.swing.JLabel next2;
    private javax.swing.JLabel next3;
    private javax.swing.JLabel next5;
    private javax.swing.JLabel next6;
    private javax.swing.JLabel next7;
    private javax.swing.JLabel next8;
    private javax.swing.JLabel next9;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tkeahlian;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tpas;
    private javax.swing.JTextField ttelpon;
    // End of variables declaration//GEN-END:variables
//
//    
//    public JTextField getTxttnama(){
//        return tnama;
//    }
//     public JTextField getTxttpas(){
//        return tpas;
//    }
//     
//      public JTextField getTxttemail(){
//        return temail;
//    }
//     
//      public JTextField getTxtttelpon(){
//        return ttelpon;
//    }
//       public JTextField getTxttkeahlian(){
//        return tkeahlian;
//    }
}
