/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ListPekerjaController;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.ListPekerjaModel;
import model.UserModel;

/**
 *
 * @author MELON
 */
public class ListPekerja extends javax.swing.JFrame {
       private ListPekerjaController listpekerjacontroller;
         private ListPekerjaModel pekerjamodel;

    /**
     * Creates new form ListPekerja
     */
    public ListPekerja() {
        initComponents();
        
        
         member.setText("Selamat Datang " + UserModel.getUsernameUser()+ " (Bisnis) ");
                 listpekerjacontroller = new ListPekerjaController (this);
                 listpekerjacontroller.isiTabellistpekerja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        next4 = new javax.swing.JLabel();
        Selesai = new javax.swing.JButton();
        next3 = new javax.swing.JLabel();
        next5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPekerja = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        next2 = new javax.swing.JLabel();
        member = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        next11 = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();
        KlikListKerja = new javax.swing.JLabel();
        KlikListPostingan = new javax.swing.JLabel();
        KlikEdittakun = new javax.swing.JLabel();
        KlikTambahPostingan = new javax.swing.JLabel();
        Txtidkerja = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        next4.setBackground(new java.awt.Color(255, 255, 255));
        next4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        next4.setForeground(new java.awt.Color(255, 255, 255));
        next4.setText("Berisi daftar pekerja yang sedang bekerja sesuai postingan");
        getContentPane().add(next4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 340, 30));

        Selesai.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        Selesai.setText("Selesai");
        Selesai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(Selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 570, 100, 30));

        next3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next3.setForeground(new java.awt.Color(255, 255, 255));
        next3.setText("List Pekerja Yang Sedang Aktif");
        getContentPane().add(next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 310, 30));

        next5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next5.setForeground(new java.awt.Color(255, 255, 255));
        next5.setText("List Pekerja");
        getContentPane().add(next5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 150, 30));

        ListPekerja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListPekerja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Email", "No Hp", "Judul Pekerjaan"
            }
        ));
        ListPekerja.setRowHeight(40);
        ListPekerja.setSelectionBackground(new java.awt.Color(24, 32, 38));
        ListPekerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListPekerjaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListPekerja);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 1030, 190));

        jPanel11.setBackground(new java.awt.Color(24, 32, 38));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        next2.setBackground(new java.awt.Color(24, 32, 38));
        next2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next2.setForeground(new java.awt.Color(255, 255, 255));
        next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-logout-rounded-left-25.png"))); // NOI18N
        next2.setText("Logout");
        next2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(next2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(next2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 620, 90, 40));

        member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("Nama Login");
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 320, 50));

        jPanel1.setBackground(new java.awt.Color(24, 43, 54));

        next11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next11.setForeground(new java.awt.Color(255, 255, 255));
        next11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-permanent-job-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(next11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(next11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 182, 150, 150));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HDBisnis.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        KlikListKerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikListKerjaMouseClicked(evt);
            }
        });
        getContentPane().add(KlikListKerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 30));

        KlikListPostingan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikListPostinganMouseClicked(evt);
            }
        });
        getContentPane().add(KlikListPostingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, 30));

        KlikEdittakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikEdittakunMouseClicked(evt);
            }
        });
        getContentPane().add(KlikEdittakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 130, 40));

        KlikTambahPostingan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikTambahPostinganMouseClicked(evt);
            }
        });
        getContentPane().add(KlikTambahPostingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, 30));

        Txtidkerja.setText("Txtidkerja");
        Txtidkerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidkerjaActionPerformed(evt);
            }
        });
        getContentPane().add(Txtidkerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
     listpekerjacontroller.DataListKerja(Integer.parseInt(Txtidkerja.getText())); 
        boolean hasil = listpekerjacontroller.deletepekerja();
    if (hasil){
    JOptionPane.showMessageDialog(null, "List Berhasill Dihapus");    
    ListPekerja home = new ListPekerja();
    home.setVisible(true);
    this.dispose();
    }else {
    JOptionPane.showMessageDialog(null, "List Gagal Dihapus"); 
    }
    }//GEN-LAST:event_SelesaiActionPerformed

    private void KlikListKerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikListKerjaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KlikListKerjaMouseClicked

    private void KlikListPostinganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikListPostinganMouseClicked
        new ListPostinganSingle().show();
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_KlikListPostinganMouseClicked

    private void KlikEdittakunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikEdittakunMouseClicked
 new EditAkunBisnis().show();
      this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_KlikEdittakunMouseClicked

    private void KlikTambahPostinganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikTambahPostinganMouseClicked
        new TambahPostingan().show();
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_KlikTambahPostinganMouseClicked

    private void ListPekerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListPekerjaMouseClicked
      listpekerjacontroller.isiid(ListPekerja.getSelectedRow());
    }//GEN-LAST:event_ListPekerjaMouseClicked

    private void TxtidkerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidkerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtidkerjaActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPekerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPekerja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel KlikEdittakun;
    private javax.swing.JLabel KlikListKerja;
    private javax.swing.JLabel KlikListPostingan;
    private javax.swing.JLabel KlikTambahPostingan;
    private javax.swing.JTable ListPekerja;
    private javax.swing.JButton Selesai;
    private javax.swing.JTextField Txtidkerja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel member;
    private javax.swing.JLabel next11;
    private javax.swing.JLabel next2;
    private javax.swing.JLabel next3;
    private javax.swing.JLabel next4;
    private javax.swing.JLabel next5;
    // End of variables declaration//GEN-END:variables

   public JTable getTabelDataListPekerja() {
        return ListPekerja;
    }
   
      public JTextField getTxtidkerja(){
        return Txtidkerja;
    }


      
      
      

}
