/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ListPekerjaanController;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.ListPekerjaanModel;
import model.UserModel;

/**
 *
 * @author MELON
 */
public class ListPekerjaan extends javax.swing.JFrame {
   private ListPekerjaanController listpekerjaancontroller;
   private ListPekerjaanModel pekerjaanmodel;
   private String[] tabelHeader;
   private DefaultTableModel dtm;
   private String path;
   private ArrayList <ListPekerjaanModel> listdatakerja1 ;
   private int noPost;
   private int jumlah;
    /**
     * Creates new form ListPekerjaan
     */
    public ListPekerjaan() {
        initComponents();
          member.setText("Selamat Datang " + UserModel.getUsernameUser()+ " (Pekerja) ");
        listpekerjaancontroller = new ListPekerjaanController (this);
     listpekerjaancontroller.isiTabellist();

   
     
//       tabelHeader = new String []{"Judul Pekerjaan", "Lokasi", "Nama Perusahaan","Deskripsi","email","contak","deadline","gambar"  };
//       dtm = new DefaultTableModel(null, tabelHeader);
//       noPost = 0;
//        Jtes.setModel(dtm);
////       tampilPost();
     
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listkerja = new javax.swing.JTable();
        Selesai = new javax.swing.JButton();
        NamaPerusahaan = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        KlikTemukan = new javax.swing.JLabel();
        KlikListP = new javax.swing.JLabel();
        KlikCatatan = new javax.swing.JLabel();
        KlikEdit = new javax.swing.JLabel();
        next3 = new javax.swing.JLabel();
        JudulP = new javax.swing.JLabel();
        Lokasi = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Deskripsi = new javax.swing.JTextArea();
        contac1 = new javax.swing.JLabel();
        deadline = new javax.swing.JLabel();
        contak = new javax.swing.JLabel();
        deadline1 = new javax.swing.JLabel();
        Des = new javax.swing.JLabel();
        Lok = new javax.swing.JLabel();
        Logdat = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        next2 = new javax.swing.JLabel();
        member = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();
        Txtidlist = new javax.swing.JTextField();
        tes = new javax.swing.JScrollPane();
        Jtes = new javax.swing.JTable();
        next = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listkerja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listkerja.setRowHeight(30);
        listkerja.setSelectionBackground(new java.awt.Color(24, 32, 38));
        listkerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listkerjaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listkerja);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 1030, 160));

        Selesai.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        Selesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-checkmark-16.png"))); // NOI18N
        Selesai.setText("Selesai");
        Selesai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(Selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 100, 50));

        NamaPerusahaan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NamaPerusahaan.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan.setText("Perusahaan");
        getContentPane().add(NamaPerusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 260, 30));

        l2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 20, 30));

        KlikTemukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikTemukanMouseClicked(evt);
            }
        });
        getContentPane().add(KlikTemukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, 30));

        KlikListP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikListPMouseClicked(evt);
            }
        });
        getContentPane().add(KlikListP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 30));

        KlikCatatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikCatatanMouseClicked(evt);
            }
        });
        getContentPane().add(KlikCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 30));

        KlikEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikEditMouseClicked(evt);
            }
        });
        getContentPane().add(KlikEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 110, 40));

        next3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next3.setForeground(new java.awt.Color(255, 255, 255));
        next3.setText("List Pekerjaan");
        getContentPane().add(next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 150, 30));

        JudulP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JudulP.setForeground(new java.awt.Color(255, 255, 255));
        JudulP.setText("Judul Pekerjaan");
        getContentPane().add(JudulP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 440, 30));

        Lokasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lokasi.setForeground(new java.awt.Color(255, 255, 255));
        Lokasi.setText("Lokasi");
        getContentPane().add(Lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 90, 30));

        Email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 130, 30));

        l1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 20, 30));

        Deskripsi.setEditable(false);
        Deskripsi.setBackground(new java.awt.Color(24, 43, 54));
        Deskripsi.setColumns(20);
        Deskripsi.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi.setRows(5);
        jScrollPane1.setViewportView(Deskripsi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 520, 200));

        contac1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contac1.setForeground(new java.awt.Color(255, 255, 255));
        contac1.setText("Deadline :");
        getContentPane().add(contac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 60, 30));

        deadline.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deadline.setForeground(new java.awt.Color(255, 255, 255));
        deadline.setText("deadline");
        getContentPane().add(deadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 90, 30));

        contak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contak.setForeground(new java.awt.Color(255, 255, 255));
        contak.setText("contak");
        getContentPane().add(contak, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 160, 30));

        deadline1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deadline1.setForeground(new java.awt.Color(255, 255, 255));
        deadline1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-ios-16.png"))); // NOI18N
        getContentPane().add(deadline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 20, 30));

        Des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Des.setForeground(new java.awt.Color(255, 255, 255));
        Des.setText("Deskripsi");
        getContentPane().add(Des, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 60, 30));

        Lok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Lok.setForeground(new java.awt.Color(255, 255, 255));
        Lok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        getContentPane().add(Lok, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 20, 30));

        Logdat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logdat.setForeground(new java.awt.Color(255, 255, 255));
        Logdat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-planner-16.png"))); // NOI18N
        getContentPane().add(Logdat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 20, 30));

        jPanel11.setBackground(new java.awt.Color(24, 32, 38));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        next2.setBackground(new java.awt.Color(24, 32, 38));
        next2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next2.setForeground(new java.awt.Color(255, 255, 255));
        next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-logout-rounded-left-25.png"))); // NOI18N
        next2.setText("Logout");
        next2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        next2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(next2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(next2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 620, 90, 40));

        member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("Nama Login");
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 320, 50));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HDUser.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Txtidlist.setText("2");
        Txtidlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidlistActionPerformed(evt);
            }
        });
        getContentPane().add(Txtidlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 520, 50, 30));

        Jtes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tes.setViewportView(Jtes);

        getContentPane().add(tes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, 40));

        next.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next >");
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 70, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("< Back");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
    listpekerjaancontroller.DataList(Integer.parseInt(Txtidlist.getText())); 
        boolean hasil = listpekerjaancontroller.deletlist();
    if (hasil){
    JOptionPane.showMessageDialog(null, "List Berhasill Dihapus");    
    ListPekerjaan home = new ListPekerjaan();
    home.setVisible(true);
    this.dispose();
    }else {
    JOptionPane.showMessageDialog(null, "List Gagal Dihapus"); 
    }// TODO add your handling code here:
    }//GEN-LAST:event_SelesaiActionPerformed

    private void KlikTemukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikTemukanMouseClicked
        new Temukan().show();
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_KlikTemukanMouseClicked

    private void KlikListPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikListPMouseClicked
        new ListPekerjaan().show();
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_KlikListPMouseClicked

    private void KlikCatatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikCatatanMouseClicked
        new Catatan().show();
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_KlikCatatanMouseClicked

    private void KlikEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikEditMouseClicked
    new EditAkunUser().show();
        this.dispose();
            
    }//GEN-LAST:event_KlikEditMouseClicked

    private void listkerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listkerjaMouseClicked
    listpekerjaancontroller.isiid(listkerja.getSelectedRow()); // TODO add your handling code here:
    }//GEN-LAST:event_listkerjaMouseClicked

    private void TxtidlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidlistActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_TxtidlistActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void next2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_next2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPekerjaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPekerjaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPekerjaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPekerjaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPekerjaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Des;
    private javax.swing.JTextArea Deskripsi;
    private javax.swing.JLabel Email;
    private javax.swing.JTable Jtes;
    private javax.swing.JLabel JudulP;
    private javax.swing.JLabel KlikCatatan;
    private javax.swing.JLabel KlikEdit;
    private javax.swing.JLabel KlikListP;
    private javax.swing.JLabel KlikTemukan;
    private javax.swing.JLabel Logdat;
    private javax.swing.JLabel Lok;
    private javax.swing.JLabel Lokasi;
    private javax.swing.JLabel NamaPerusahaan;
    private javax.swing.JButton Selesai;
    private javax.swing.JTextField Txtidlist;
    private javax.swing.JLabel back;
    private javax.swing.JLabel contac1;
    private javax.swing.JLabel contak;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel deadline1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTable listkerja;
    private javax.swing.JLabel member;
    private javax.swing.JLabel next;
    private javax.swing.JLabel next2;
    private javax.swing.JLabel next3;
    private javax.swing.JScrollPane tes;
    // End of variables declaration//GEN-END:variables

   public JTable getTabelDataListPekerja() {
        return listkerja;
    }

      public JTextField getTxtidpost(){
        return Txtidlist;
    }

    public JLabel getTxtjudul(){
        return JudulP;
    }
     public JLabel getTxtnamap(){
        return NamaPerusahaan;
    }
      public JLabel getTxtlokasi(){
        return Lokasi;
    }
         public JLabel getTxtemail(){
        return Email;
    }
         public JLabel getTxtkontak(){
        return contak;
    }
     public JLabel getTxtdeadline(){
        return deadline;
    }
     
          public JTextArea getTxtdeskripsi(){
        return Deskripsi;
    }
       
      
      
      
//    public void tampilData(int index,JLabel JudulP,JTextArea Dekripsi, JLabel NamaPerusahaan,  JLabel Lokasi,
//                JLabel Email,JLabel contac ,JLabel deadline,String nama, JLabel logo
//    ){
//        JudulP.setText(dtm.getValueAt(index, 0).toString());
//        Lokasi.setText(dtm.getValueAt(index, 1).toString());
//        NamaPerusahaan.setText(dtm.getValueAt(index, 2).toString());
//        Dekripsi.setText(dtm.getValueAt(index, 3).toString());
//        Email.setText(dtm.getValueAt(index, 4).toString());
//        contac.setText(dtm.getValueAt(index, 5).toString());
//        deadline.setText(dtm.getValueAt(index, 6).toString());
//        Toolkit tool = Toolkit.getDefaultToolkit();
//        path = "src/image/";
//        Image img = tool.getImage(path + nama);
//        Image imagedResized=img.getScaledInstance (logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon imageIcon = new ImageIcon(imagedResized);
//        logo.setIcon(imageIcon);
//        
//     
//    }
//    
//       public void postKosong(JLabel JudulP, JTextArea Dekripsi, JLabel NamaPerusahaan,  JLabel Lokasi,JLabel Email,JLabel contac,JLabel deadline, JLabel logo
//    ){
//        JudulP.setText("");
//        Dekripsi.setText("");
//        NamaPerusahaan.setText("");
//        Lokasi.setText("");
//        Email.setText("");
//        contac.setText("");
//        deadline.setText("");
//
//        Toolkit tool = Toolkit.getDefaultToolkit();
//        path = "src/image/";
//        Image img = tool.getImage(path + "NO foto");
//        Image imagedResized=img.getScaledInstance (logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon imageIcon=new    ImageIcon(imagedResized);
//        logo.setIcon(imageIcon);
//    }
//      
// 
//         
//      public void tampilPost(){
//        dtm = (DefaultTableModel) Jtes.getModel();
//         dtm.setRowCount(0);
//         listdatakerja1 = listpekerjaancontroller.DataKerjaan1();
//         for (ListPekerjaanModel data : listdatakerja1){
//             dtm.addRow(new Object[]{
//             data.getJudul1(),
//             data.getLocation1(),
//             data.getNama_perusahaan1(),
//             data.getDeskripsi1(),
//             data.getEmail1(),
//             data.getContact1(),
//             data.getDeadline1(),
//             data.getLogo1()
//          
//             });
//            }
//         
//                  jumlah = dtm.getRowCount();
//        if (noPost<jumlah)  {
//         tampilData(noPost, JudulP,Deskripsi,NamaPerusahaan,Lokasi,
//        contac,deadline,email,  (String) dtm.getValueAt(noPost,7),Logo1);
//           } else{
//           postKosong( JudulP,Deskripsi,NamaPerusahaan,Lokasi,
//        contac,deadline,email,Logo1);
//           }    
////           tampilData(noPost, JudulP,Deskripsi,NamaPerusahaan,Lokasi,
////        contac,deadline,email,  (String) dtm.getValueAt(noPost,7),Logo1);
//           
//      
//      }

  
 
      
      
      
}
