/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.UserController;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author MELON
 */
public class Register extends javax.swing.JFrame {
      UserController usercontrol;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        usercontrol = new UserController (this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RdPerusahaan = new javax.swing.JRadioButton();
        RdPekerja = new javax.swing.JRadioButton();
        KlikLogin = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tpas = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        ttelpon = new javax.swing.JTextField();
        tkeahlian = new javax.swing.JTextField();
        Des1 = new javax.swing.JLabel();
        Des = new javax.swing.JLabel();
        Regis = new javax.swing.JLabel();
        Log = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RdPerusahaan.setForeground(new java.awt.Color(255, 255, 255));
        RdPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdPerusahaanActionPerformed(evt);
            }
        });
        getContentPane().add(RdPerusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        RdPekerja.setForeground(new java.awt.Color(255, 255, 255));
        RdPekerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdPekerjaActionPerformed(evt);
            }
        });
        getContentPane().add(RdPekerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        KlikLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikLoginMouseClicked(evt);
            }
        });
        getContentPane().add(KlikLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 160, 40));

        tnama.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 240, 30));

        tpas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasActionPerformed(evt);
            }
        });
        getContentPane().add(tpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 240, 30));

        temail.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 240, 30));

        ttelpon.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        getContentPane().add(ttelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 240, 30));

        tkeahlian.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        getContentPane().add(tkeahlian, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 240, 30));

        Des1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Des1.setForeground(new java.awt.Color(255, 255, 255));
        Des1.setText("Pekerja");
        getContentPane().add(Des1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 60, 40));

        Des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Des.setForeground(new java.awt.Color(255, 255, 255));
        Des.setText("Bisnis");
        getContentPane().add(Des, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 60, 40));

        Regis.setBackground(new java.awt.Color(24, 32, 38));
        Regis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Regis.setForeground(new java.awt.Color(255, 255, 255));
        Regis.setText("                       Daftar");
        Regis.setToolTipText("");
        Regis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Regis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisMouseClicked(evt);
            }
        });
        getContentPane().add(Regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 240, 30));

        Log.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Log.setForeground(new java.awt.Color(255, 255, 255));
        Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogMouseClicked(evt);
            }
        });
        getContentPane().add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 20));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/regis2.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KlikLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikLoginMouseClicked
            new Login().show();
this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_KlikLoginMouseClicked

    private void RdPekerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdPekerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdPekerjaActionPerformed

    private void RdPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdPerusahaanActionPerformed

    private void RegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisMouseClicked
 int level = 0;
    if (RdPekerja.isSelected() == true ){
    level = 1 ;
    }else if (RdPerusahaan.isSelected() == true ){
        level = 2 ;
    }
   
    if (level == 0){
    JOptionPane.showMessageDialog(null, "Pilih akun gan");
    

    }
        else{
        
        
    boolean hasil = false;

   
   usercontrol.DataUser(tnama.getText(), tpas.getText(), temail.getText(), ttelpon.getText(),tkeahlian.getText(), level);
   hasil = usercontrol.insertUser();
    if (hasil){
    JOptionPane.showMessageDialog(null, "Register Berhasill");    
    Login home = new Login();
    home.setVisible(true);
    this.dispose();
    }else {
    JOptionPane.showMessageDialog(null, "Register Gagal");
    tnama.setText(null);
    tpas.setText(null);
    tnama.requestFocus();
    }
    }       // TODO add your handling code here:
    }//GEN-LAST:event_RegisMouseClicked

    private void tpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasActionPerformed

    private void LogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogMouseClicked
new Login().show();
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_LogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel Des;
    private javax.swing.JLabel Des1;
    private javax.swing.JLabel KlikLogin;
    private javax.swing.JLabel Log;
    private javax.swing.JRadioButton RdPekerja;
    private javax.swing.JRadioButton RdPerusahaan;
    private javax.swing.JLabel Regis;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tkeahlian;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tpas;
    private javax.swing.JTextField ttelpon;
    // End of variables declaration//GEN-END:variables
}
