/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import control.PostingController;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.UserModel;
import org.apache.commons.io.FileUtils;
/**
 *
 * @author MELON
 */
public class TambahPostingan extends javax.swing.JFrame {
    PostingController postingcontroller;
    JFileChooser jfc;
    File file;
    /**
     * Creates new form TambahPostingan
     */
    public TambahPostingan() {
        initComponents();
         postingcontroller = new PostingController (this);
                   member.setText("Selamat Datang " + UserModel.getUsernameUser()+ " (Bisnis) ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        member = new javax.swing.JLabel();
        KlikListKerja = new javax.swing.JLabel();
        KlikListPostingan = new javax.swing.JLabel();
        KlikEdittakun = new javax.swing.JLabel();
        KlikTambahPostingan = new javax.swing.JLabel();
        KlikPostingan = new javax.swing.JLabel();
        KlikEditAkun = new javax.swing.JLabel();
        next3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Deadline = new com.toedter.calendar.JDateChooser();
        judulpost = new javax.swing.JTextField();
        Company = new javax.swing.JTextField();
        Cilent = new javax.swing.JTextField();
        Pays = new javax.swing.JTextField();
        Location = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        Description = new javax.swing.JScrollPane();
        Deskripsi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        Btnupload = new javax.swing.JButton();
        txtGambar = new javax.swing.JTextField();
        KlikBatal = new javax.swing.JLabel();
        KlikSimpan = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        next2 = new javax.swing.JLabel();
        Backgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("Nama Login");
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 320, 40));

        KlikListKerja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikListKerjaMouseClicked(evt);
            }
        });
        getContentPane().add(KlikListKerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 30));

        KlikListPostingan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikListPostinganMouseClicked(evt);
            }
        });
        getContentPane().add(KlikListPostingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, 30));

        KlikEdittakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikEdittakunMouseClicked(evt);
            }
        });
        getContentPane().add(KlikEdittakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 130, 40));

        KlikTambahPostingan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikTambahPostinganMouseClicked(evt);
            }
        });
        getContentPane().add(KlikTambahPostingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, 30));

        KlikPostingan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikPostinganMouseClicked(evt);
            }
        });
        getContentPane().add(KlikPostingan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 90, 30));

        KlikEditAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikEditAkunMouseClicked(evt);
            }
        });
        getContentPane().add(KlikEditAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 120, 30));

        next3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next3.setText("Tambah Postingan");
        getContentPane().add(next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 160, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Decription");

        judulpost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));
        judulpost.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        judulpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulpostActionPerformed(evt);
            }
        });

        Company.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));
        Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyActionPerformed(evt);
            }
        });

        Cilent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));

        Pays.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));
        Pays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaysActionPerformed(evt);
            }
        });

        Location.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));
        Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationActionPerformed(evt);
            }
        });

        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));

        Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));

        Deskripsi.setColumns(20);
        Deskripsi.setRows(5);
        Deskripsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));
        Description.setViewportView(Deskripsi);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Job Title ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setText("Pays");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setText("Client");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setText("Deadline");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setText("Company");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setText("Location");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel9.setText("Contact");

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        jButton2.setText("Simpan");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        jButton1.setText("Batal");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Logo.setBackground(new java.awt.Color(0, 0, 0));
        Logo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/iconfinder_icon-image_211677 (1).png"))); // NOI18N
        Logo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 44, 56), 2, true));

        Btnupload.setText("Upload Foto");
        Btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnuploadActionPerformed(evt);
            }
        });

        txtGambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 44, 56), 2));

        KlikBatal.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        KlikBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikBatalMouseClicked(evt);
            }
        });

        KlikSimpan.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        KlikSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Contact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btnupload)
                                    .addComponent(txtGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description)
                            .addComponent(judulpost)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(Pays, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cilent, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGap(89, 89, 89)
                .addComponent(KlikSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KlikBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(judulpost, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pays, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(Btnupload)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Cilent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Company, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KlikBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KlikSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 1050, 570));

        jPanel11.setBackground(new java.awt.Color(24, 32, 38));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        next2.setBackground(new java.awt.Color(24, 32, 38));
        next2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next2.setForeground(new java.awt.Color(255, 255, 255));
        next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-logout-rounded-left-25.png"))); // NOI18N
        next2.setText("Logout");
        next2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(next2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(next2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 620, 90, 40));

        Backgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HDBisnis.png"))); // NOI18N
        getContentPane().add(Backgrond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KlikListKerjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikListKerjaMouseClicked
  new ListPekerja().show();
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_KlikListKerjaMouseClicked

    private void KlikListPostinganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikListPostinganMouseClicked
        new ListPostinganSingle().show();
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_KlikListPostinganMouseClicked

    private void KlikEdittakunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikEdittakunMouseClicked
 new EditAkunBisnis().show();
      this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_KlikEdittakunMouseClicked

    private void KlikTambahPostinganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikTambahPostinganMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_KlikTambahPostinganMouseClicked

    private void KlikPostinganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikPostinganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KlikPostinganMouseClicked

    private void KlikEditAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikEditAkunMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KlikEditAkunMouseClicked

    private void KlikSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikSimpanMouseClicked
    
        
  
   

    }//GEN-LAST:event_KlikSimpanMouseClicked

    private void KlikBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikBatalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KlikBatalMouseClicked

    private void judulpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulpostActionPerformed

    private void PaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaysActionPerformed

    private void LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyActionPerformed

    private void BtnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnuploadActionPerformed

  jfc = new JFileChooser();
  if(jfc.showOpenDialog(Logo)== JFileChooser.APPROVE_OPTION){
  Toolkit tool = Toolkit.getDefaultToolkit();
  Image img = tool.getImage(jfc.getSelectedFile().getAbsolutePath());
  Image imagedResized=img.getScaledInstance (Logo.getWidth(), Logo.getHeight(), Image.SCALE_SMOOTH);
  ImageIcon imageIcon = new    ImageIcon(imagedResized);
  
  Logo.setIcon (imageIcon);
  txtGambar.setText(jfc.getSelectedFile().getName());
  
  file= new File(jfc.getSelectedFile().getPath());
  }

//        JFileChooser fileChooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Exstension Supported ", "jpg","jpeg");
//        fileChooser.setFileFilter(filter);
//        int selected = fileChooser.showOpenDialog(null);
//        if (selected == JFileChooser.APPROVE_OPTION){
//        File file = fileChooser.getSelectedFile();
//        String getselectedImage = file.getAbsolutePath();
//        ImageIcon imIco = new ImageIcon(getselectedImage);
//        Image imFit = imIco.getImage();
//        Image imgFit = imFit.getScaledInstance(Logo.getWidth(), Logo.getHeight(), Image.SCALE_SMOOTH);
//        Logo.setIcon(new ImageIcon(imgFit));
//        
//        
//        
//        }        
    }//GEN-LAST:event_BtnuploadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(Deskripsi.getText().equals(""))  //Jika Nilai Yang diambil pada TxtNama Kosong ("")
        {
            JOptionPane.showMessageDialog(null,"judulpost tidak bolek kosong ");
        }else if(judulpost.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Deskripsi tidak bolek kosong ");
        }
        else if(Deskripsi.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Deskripsi tidak bolek kosong ");
        }
        else if(Pays.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Pays tidak bolek kosong ");
        }
        else if(Cilent.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Cilent tidak bolek kosong ");
        }
        else if(Company.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Company tidak bolek kosong ");
        }
        else if(Location.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Location tidak bolek kosong ");
        }
         else if(Email.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Email tidak bolek kosong ");
        }
         
         else if(Contact.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Contact tidak bolek kosong ");
        }
          else if(txtGambar.getText().equals(""))
         {
            JOptionPane.showMessageDialog(null,"Gambar tidak bolek kosong ");
        }
         
        else{
   boolean hasil = false;
    String deadline ;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    deadline = sdf.format (Deadline.getDate());

    try {
    String path=new File(".").getCanonicalPath();
     FileUtils.copyFileToDirectory(file, new File("src/image"));
    } catch (IOException ex){
    }
              
              
            postingcontroller.DataPosting(Deskripsi.getText(), judulpost.getText(), Pays.getText(),Cilent.getText(), Company.getText(), Location.getText(), Email.getText(), Contact.getText(),deadline, txtGambar.getText());
        //    postingmodel.DataPosting(Deskripsi.getText(),judulpost.getText(), Pays.getText(), Cilent.getText(), Commission.getText(), Location.getText(), Email.getText(), Contact.getText(),deadline);
            hasil = postingcontroller.InsertPosting();  
               if (hasil){
            JOptionPane.showMessageDialog(null, "Data masuk GAN :)");    
            TambahPostingan home = new TambahPostingan();
            home.setVisible(true);
            this.dispose();
            }else {
            JOptionPane.showMessageDialog(null, "Data gagal masuk Gagal");
    }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPostingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPostingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPostingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPostingan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPostingan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgrond;
    private javax.swing.JButton Btnupload;
    private javax.swing.JTextField Cilent;
    private javax.swing.JTextField Company;
    private javax.swing.JTextField Contact;
    private com.toedter.calendar.JDateChooser Deadline;
    private javax.swing.JScrollPane Description;
    private javax.swing.JTextArea Deskripsi;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel KlikBatal;
    private javax.swing.JLabel KlikEditAkun;
    private javax.swing.JLabel KlikEdittakun;
    private javax.swing.JLabel KlikListKerja;
    private javax.swing.JLabel KlikListPostingan;
    private javax.swing.JLabel KlikPostingan;
    private javax.swing.JLabel KlikSimpan;
    private javax.swing.JLabel KlikTambahPostingan;
    private javax.swing.JTextField Location;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Pays;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JTextField judulpost;
    private javax.swing.JLabel member;
    private javax.swing.JLabel next2;
    private javax.swing.JLabel next3;
    private javax.swing.JTextField txtGambar;
    // End of variables declaration//GEN-END:variables





}
