/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.UserModel;
import control.DataPostController;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.DataPosting;
import model.PostingModel;


/**
 *
 * @author MELON
 */
public class Temukan extends javax.swing.JFrame {
  
    private DataPostController dataposcontrol;
    private ArrayList <DataPosting> listdata;
    private int noPost;
    private int jumlah;
    private String[] tabelHeader;
    private DefaultTableModel dtm;
    private String path;

   
    /**
     * Creates new form Temukan
     */
    public Temukan() {
        initComponents();

        member.setText("Selamat Datang " + UserModel.getUsernameUser()+ " (Pekerja) ");
 
     
  dataposcontrol = new DataPostController(this);
        tabelHeader = new String []{"Judul Pekerjaan", "Deskripsi", "Nama Perusahaan", "alamat","gambar","id_post","pays","email"};
        dtm = new DefaultTableModel(null, tabelHeader);
        noPost = 0;
        tblPost.setModel(dtm);
         tampilPost();
        
                }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        member = new javax.swing.JLabel();
        KlikTemukan = new javax.swing.JLabel();
        KlikListP = new javax.swing.JLabel();
        KlikCatatan = new javax.swing.JLabel();
        KlikEdit = new javax.swing.JLabel();
        next1 = new javax.swing.JLabel();
        next3 = new javax.swing.JLabel();
        next4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        Pays1 = new javax.swing.JLabel();
        NamaPerusahaan1 = new javax.swing.JLabel();
        JudulPekerjaan1 = new javax.swing.JLabel();
        Deskripsi1 = new javax.swing.JLabel();
        TambahKeLiist1 = new javax.swing.JButton();
        Alamat1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Logo3 = new javax.swing.JLabel();
        NamaPerusahaan3 = new javax.swing.JLabel();
        JudulPekerjaan3 = new javax.swing.JLabel();
        Deskripsi3 = new javax.swing.JLabel();
        TambahKeLiist3 = new javax.swing.JButton();
        Alamat3 = new javax.swing.JLabel();
        Pays3 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l31 = new javax.swing.JLabel();
        Email3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Logo4 = new javax.swing.JLabel();
        NamaPerusahaan4 = new javax.swing.JLabel();
        JudulPekerjaan4 = new javax.swing.JLabel();
        Deskripsi4 = new javax.swing.JLabel();
        TambahKeLiist4 = new javax.swing.JButton();
        Alamat4 = new javax.swing.JLabel();
        Pays4 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l32 = new javax.swing.JLabel();
        Email4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Logo2 = new javax.swing.JLabel();
        NamaPerusahaan2 = new javax.swing.JLabel();
        JudulPekerjaan2 = new javax.swing.JLabel();
        Deskripsi2 = new javax.swing.JLabel();
        TambahKeLiist2 = new javax.swing.JButton();
        Alamat2 = new javax.swing.JLabel();
        Pays2 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l30 = new javax.swing.JLabel();
        Email2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Logo5 = new javax.swing.JLabel();
        NamaPerusahaan5 = new javax.swing.JLabel();
        JudulPekerjaan5 = new javax.swing.JLabel();
        Deskripsi5 = new javax.swing.JLabel();
        TambahKeLiist5 = new javax.swing.JButton();
        Alamat5 = new javax.swing.JLabel();
        Pays5 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l33 = new javax.swing.JLabel();
        Email5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Logo6 = new javax.swing.JLabel();
        NamaPerusahaan6 = new javax.swing.JLabel();
        JudulPekerjaan6 = new javax.swing.JLabel();
        Deskripsi6 = new javax.swing.JLabel();
        TambahKeLiist6 = new javax.swing.JButton();
        Alamat6 = new javax.swing.JLabel();
        Pays6 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        l34 = new javax.swing.JLabel();
        Email6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Logo7 = new javax.swing.JLabel();
        NamaPerusahaan7 = new javax.swing.JLabel();
        JudulPekerjaan7 = new javax.swing.JLabel();
        Deskripsi7 = new javax.swing.JLabel();
        TambahKeLiist7 = new javax.swing.JButton();
        Alamat7 = new javax.swing.JLabel();
        Pays7 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l27 = new javax.swing.JLabel();
        l35 = new javax.swing.JLabel();
        Email7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Logo8 = new javax.swing.JLabel();
        NamaPerusahaan8 = new javax.swing.JLabel();
        JudulPekerjaan8 = new javax.swing.JLabel();
        Deskripsi8 = new javax.swing.JLabel();
        TambahKeLiist8 = new javax.swing.JButton();
        Alamat8 = new javax.swing.JLabel();
        Pays8 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l28 = new javax.swing.JLabel();
        l36 = new javax.swing.JLabel();
        Email8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Logo9 = new javax.swing.JLabel();
        NamaPerusahaan9 = new javax.swing.JLabel();
        JudulPekerjaan9 = new javax.swing.JLabel();
        Deskripsi9 = new javax.swing.JLabel();
        TambahKeLiist9 = new javax.swing.JButton();
        Alamat9 = new javax.swing.JLabel();
        Pays9 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l29 = new javax.swing.JLabel();
        l37 = new javax.swing.JLabel();
        Email9 = new javax.swing.JLabel();
        next5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        next2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPost = new javax.swing.JTable();
        next = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Id1 = new javax.swing.JTextField();
        Id3 = new javax.swing.JTextField();
        Id2 = new javax.swing.JTextField();
        Id4 = new javax.swing.JTextField();
        Id5 = new javax.swing.JTextField();
        Id6 = new javax.swing.JTextField();
        Id7 = new javax.swing.JTextField();
        Id8 = new javax.swing.JTextField();
        Id9 = new javax.swing.JTextField();
        Id10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        member.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("Nama Login");
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 320, 50));

        KlikTemukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikTemukanMouseClicked(evt);
            }
        });
        getContentPane().add(KlikTemukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 230, 30));

        KlikListP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikListPMouseClicked(evt);
            }
        });
        getContentPane().add(KlikListP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, 30));

        KlikCatatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikCatatanMouseClicked(evt);
            }
        });
        getContentPane().add(KlikCatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 30));

        KlikEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KlikEditMouseClicked(evt);
            }
        });
        getContentPane().add(KlikEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 110, 40));

        next1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next1.setForeground(new java.awt.Color(255, 255, 255));
        next1.setText("Logo");
        getContentPane().add(next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 70, 30));

        next3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next3.setForeground(new java.awt.Color(255, 255, 255));
        next3.setText("Deskripsi");
        getContentPane().add(next3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 100, 30));

        next4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next4.setForeground(new java.awt.Color(255, 255, 255));
        next4.setText("Nama Perusahaan");
        getContentPane().add(next4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 150, 130, 30));

        jPanel2.setBackground(new java.awt.Color(24, 32, 38));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setBackground(new java.awt.Color(0, 0, 0));
        Logo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        l10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel2.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 90, 90));

        Pays1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays1.setForeground(new java.awt.Color(255, 255, 255));
        Pays1.setText("Rp .");
        jPanel2.add(Pays1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 200, 40));

        NamaPerusahaan1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan1.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan1.setText("Nama Perusahaan");
        jPanel2.add(NamaPerusahaan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 280, 40));

        JudulPekerjaan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan1.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan1.setText("Judul Pekerjaan ");
        jPanel2.add(JudulPekerjaan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 230, 40));

        Deskripsi1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi1.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi1.setText("Deskripsi");
        jPanel2.add(Deskripsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist1.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist1.setText("Tambah ke list");
        TambahKeLiist1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist1ActionPerformed(evt);
            }
        });
        jPanel2.add(TambahKeLiist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat1.setForeground(new java.awt.Color(255, 255, 255));
        Alamat1.setText("Alamat");
        jPanel2.add(Alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        l1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Rp .");
        jPanel2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l11.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l11.setForeground(new java.awt.Color(255, 255, 255));
        l11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel2.add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l21.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l21.setForeground(new java.awt.Color(255, 255, 255));
        l21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel2.add(l21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l20.setForeground(new java.awt.Color(255, 255, 255));
        l20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel2.add(l20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email1.setForeground(new java.awt.Color(255, 255, 255));
        Email1.setText("Email");
        jPanel2.add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel4.setBackground(new java.awt.Color(24, 32, 38));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo3.setBackground(new java.awt.Color(0, 0, 0));
        Logo3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(Logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan3.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan3.setText("Nama Perusahaan");
        jPanel4.add(NamaPerusahaan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan3.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan3.setText("Judul Pekerjaan ");
        jPanel4.add(JudulPekerjaan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 200, 40));

        Deskripsi3.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi3.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi3.setText("Deskripsi");
        jPanel4.add(Deskripsi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist3.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist3.setText("Tambah ke list");
        TambahKeLiist3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist3ActionPerformed(evt);
            }
        });
        jPanel4.add(TambahKeLiist3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat3.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat3.setForeground(new java.awt.Color(255, 255, 255));
        Alamat3.setText("Alamat");
        jPanel4.add(Alamat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays3.setForeground(new java.awt.Color(255, 255, 255));
        Pays3.setText("Rp .");
        jPanel4.add(Pays3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 200, 40));

        l3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Rp .");
        jPanel4.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l12.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 255, 255));
        l12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel4.add(l12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l23.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l23.setForeground(new java.awt.Color(255, 255, 255));
        l23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel4.add(l23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l31.setForeground(new java.awt.Color(255, 255, 255));
        l31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel4.add(l31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email3.setForeground(new java.awt.Color(255, 255, 255));
        Email3.setText("Email");
        jPanel4.add(Email3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel5.setBackground(new java.awt.Color(24, 32, 38));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo4.setBackground(new java.awt.Color(0, 0, 0));
        Logo4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(Logo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan4.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan4.setText("Nama Perusahaan");
        jPanel5.add(NamaPerusahaan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan4.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan4.setText("Judul Pekerjaan ");
        jPanel5.add(JudulPekerjaan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 200, 40));

        Deskripsi4.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi4.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi4.setText("Deskripsi");
        jPanel5.add(Deskripsi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist4.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist4.setText("Tambah ke list");
        TambahKeLiist4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist4ActionPerformed(evt);
            }
        });
        jPanel5.add(TambahKeLiist4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat4.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat4.setForeground(new java.awt.Color(255, 255, 255));
        Alamat4.setText("Alamat");
        jPanel5.add(Alamat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays4.setForeground(new java.awt.Color(255, 255, 255));
        Pays4.setText("Rp .");
        jPanel5.add(Pays4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 40));

        l4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Rp .");
        jPanel5.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l13.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l13.setForeground(new java.awt.Color(255, 255, 255));
        l13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel5.add(l13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l24.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l24.setForeground(new java.awt.Color(255, 255, 255));
        l24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel5.add(l24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l32.setForeground(new java.awt.Color(255, 255, 255));
        l32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel5.add(l32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email4.setForeground(new java.awt.Color(255, 255, 255));
        Email4.setText("Email");
        jPanel5.add(Email4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel3.setBackground(new java.awt.Color(24, 32, 38));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo2.setBackground(new java.awt.Color(0, 0, 0));
        Logo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan2.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan2.setText("Nama Perusahaan");
        jPanel3.add(NamaPerusahaan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan2.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan2.setText("Judul Pekerjaan ");
        jPanel3.add(JudulPekerjaan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 210, 40));

        Deskripsi2.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi2.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi2.setText("Deskripsi");
        jPanel3.add(Deskripsi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist2.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist2.setText("Tambah ke list");
        TambahKeLiist2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist2ActionPerformed(evt);
            }
        });
        jPanel3.add(TambahKeLiist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat2.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat2.setForeground(new java.awt.Color(255, 255, 255));
        Alamat2.setText("Alamat");
        jPanel3.add(Alamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays2.setForeground(new java.awt.Color(255, 255, 255));
        Pays2.setText("Rp .");
        jPanel3.add(Pays2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 40));

        l2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Rp .");
        jPanel3.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l14.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l14.setForeground(new java.awt.Color(255, 255, 255));
        l14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel3.add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l22.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l22.setForeground(new java.awt.Color(255, 255, 255));
        l22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel3.add(l22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l30.setForeground(new java.awt.Color(255, 255, 255));
        l30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel3.add(l30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email2.setForeground(new java.awt.Color(255, 255, 255));
        Email2.setText("Email");
        jPanel3.add(Email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel6.setBackground(new java.awt.Color(24, 32, 38));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo5.setBackground(new java.awt.Color(0, 0, 0));
        Logo5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(Logo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan5.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan5.setText("Nama Perusahaan");
        jPanel6.add(NamaPerusahaan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan5.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan5.setText("Judul Pekerjaan ");
        jPanel6.add(JudulPekerjaan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 200, 40));

        Deskripsi5.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi5.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi5.setText("Deskripsi");
        jPanel6.add(Deskripsi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist5.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist5.setText("Tambah ke list");
        TambahKeLiist5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist5ActionPerformed(evt);
            }
        });
        jPanel6.add(TambahKeLiist5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat5.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat5.setForeground(new java.awt.Color(255, 255, 255));
        Alamat5.setText("Alamat");
        jPanel6.add(Alamat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays5.setForeground(new java.awt.Color(255, 255, 255));
        Pays5.setText("Rp .");
        jPanel6.add(Pays5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 40));

        l5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("Rp .");
        jPanel6.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l15.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l15.setForeground(new java.awt.Color(255, 255, 255));
        l15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel6.add(l15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l25.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l25.setForeground(new java.awt.Color(255, 255, 255));
        l25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel6.add(l25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l33.setForeground(new java.awt.Color(255, 255, 255));
        l33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel6.add(l33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email5.setForeground(new java.awt.Color(255, 255, 255));
        Email5.setText("Email");
        jPanel6.add(Email5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel7.setBackground(new java.awt.Color(24, 32, 38));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo6.setBackground(new java.awt.Color(0, 0, 0));
        Logo6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.add(Logo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan6.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan6.setText("Nama Perusahaan");
        jPanel7.add(NamaPerusahaan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan6.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan6.setText("Judul Pekerjaan ");
        jPanel7.add(JudulPekerjaan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 200, 40));

        Deskripsi6.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi6.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi6.setText("Deskripsi");
        jPanel7.add(Deskripsi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist6.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist6.setText("Tambah ke list");
        TambahKeLiist6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist6ActionPerformed(evt);
            }
        });
        jPanel7.add(TambahKeLiist6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat6.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat6.setForeground(new java.awt.Color(255, 255, 255));
        Alamat6.setText("Alamat");
        jPanel7.add(Alamat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays6.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays6.setForeground(new java.awt.Color(255, 255, 255));
        Pays6.setText("Rp .");
        jPanel7.add(Pays6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 40));

        l6.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setText("Rp .");
        jPanel7.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l16.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l16.setForeground(new java.awt.Color(255, 255, 255));
        l16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel7.add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l26.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l26.setForeground(new java.awt.Color(255, 255, 255));
        l26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel7.add(l26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l34.setForeground(new java.awt.Color(255, 255, 255));
        l34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel7.add(l34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email6.setForeground(new java.awt.Color(255, 255, 255));
        Email6.setText("Email");
        jPanel7.add(Email6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel8.setBackground(new java.awt.Color(24, 32, 38));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo7.setBackground(new java.awt.Color(0, 0, 0));
        Logo7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(Logo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan7.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan7.setText("Nama Perusahaan");
        jPanel8.add(NamaPerusahaan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan7.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan7.setText("Judul Pekerjaan ");
        jPanel8.add(JudulPekerjaan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 200, 40));

        Deskripsi7.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi7.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi7.setText("Deskripsi");
        jPanel8.add(Deskripsi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist7.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist7.setText("Tambah ke list");
        TambahKeLiist7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist7ActionPerformed(evt);
            }
        });
        jPanel8.add(TambahKeLiist7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat7.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat7.setForeground(new java.awt.Color(255, 255, 255));
        Alamat7.setText("Alamat");
        jPanel8.add(Alamat7, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays7.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays7.setForeground(new java.awt.Color(255, 255, 255));
        Pays7.setText("Rp .");
        jPanel8.add(Pays7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 40));

        l7.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));
        l7.setText("Rp .");
        jPanel8.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l17.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l17.setForeground(new java.awt.Color(255, 255, 255));
        l17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel8.add(l17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l27.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l27.setForeground(new java.awt.Color(255, 255, 255));
        l27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel8.add(l27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l35.setForeground(new java.awt.Color(255, 255, 255));
        l35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel8.add(l35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email7.setForeground(new java.awt.Color(255, 255, 255));
        Email7.setText("Email");
        jPanel8.add(Email7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel9.setBackground(new java.awt.Color(24, 32, 38));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo8.setBackground(new java.awt.Color(0, 0, 0));
        Logo8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.add(Logo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan8.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan8.setText("Nama Perusahaan");
        jPanel9.add(NamaPerusahaan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan8.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan8.setText("Judul Pekerjaan ");
        jPanel9.add(JudulPekerjaan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 200, 40));

        Deskripsi8.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi8.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi8.setText("Deskripsi");
        jPanel9.add(Deskripsi8, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist8.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist8.setText("Tambah ke list");
        TambahKeLiist8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist8ActionPerformed(evt);
            }
        });
        jPanel9.add(TambahKeLiist8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat8.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat8.setForeground(new java.awt.Color(255, 255, 255));
        Alamat8.setText("Alamat");
        jPanel9.add(Alamat8, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays8.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays8.setForeground(new java.awt.Color(255, 255, 255));
        Pays8.setText("Rp .");
        jPanel9.add(Pays8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 40));

        l8.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));
        l8.setText("Rp .");
        jPanel9.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l18.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l18.setForeground(new java.awt.Color(255, 255, 255));
        l18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel9.add(l18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l28.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l28.setForeground(new java.awt.Color(255, 255, 255));
        l28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel9.add(l28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l36.setForeground(new java.awt.Color(255, 255, 255));
        l36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel9.add(l36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email8.setForeground(new java.awt.Color(255, 255, 255));
        Email8.setText("Email");
        jPanel9.add(Email8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        jPanel10.setBackground(new java.awt.Color(24, 32, 38));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo9.setBackground(new java.awt.Color(0, 0, 0));
        Logo9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logo9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.add(Logo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 110));

        NamaPerusahaan9.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        NamaPerusahaan9.setForeground(new java.awt.Color(255, 255, 255));
        NamaPerusahaan9.setText("Nama Perusahaan");
        jPanel10.add(NamaPerusahaan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 14, 270, 40));

        JudulPekerjaan9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulPekerjaan9.setForeground(new java.awt.Color(255, 255, 255));
        JudulPekerjaan9.setText("Judul Pekerjaan ");
        jPanel10.add(JudulPekerjaan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 14, 200, 40));

        Deskripsi9.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Deskripsi9.setForeground(new java.awt.Color(255, 255, 255));
        Deskripsi9.setText("Deskripsi");
        jPanel10.add(Deskripsi9, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 14, 300, 40));

        TambahKeLiist9.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        TambahKeLiist9.setText("Tambah ke list");
        TambahKeLiist9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TambahKeLiist9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahKeLiist9ActionPerformed(evt);
            }
        });
        jPanel10.add(TambahKeLiist9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 100, 30));

        Alamat9.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        Alamat9.setForeground(new java.awt.Color(255, 255, 255));
        Alamat9.setText("Alamat");
        jPanel10.add(Alamat9, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 74, 150, 30));

        Pays9.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        Pays9.setForeground(new java.awt.Color(255, 255, 255));
        Pays9.setText("Rp .");
        jPanel10.add(Pays9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 40));

        l9.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setText("Rp .");
        jPanel10.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 30, 40));

        l19.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l19.setForeground(new java.awt.Color(255, 255, 255));
        l19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/urban.png"))); // NOI18N
        jPanel10.add(l19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 30, 30));

        l29.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        l29.setForeground(new java.awt.Color(255, 255, 255));
        l29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-location-16.png"))); // NOI18N
        jPanel10.add(l29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 60));

        l37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l37.setForeground(new java.awt.Color(255, 255, 255));
        l37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/mail (2).png"))); // NOI18N
        jPanel10.add(l37, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 20, 30));

        Email9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Email9.setForeground(new java.awt.Color(255, 255, 255));
        Email9.setText("Email");
        jPanel10.add(Email9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 1030, 540));

        next5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next5.setForeground(new java.awt.Color(255, 255, 255));
        next5.setText("Nama pekerjaan");
        getContentPane().add(next5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 130, 30));

        jPanel11.setBackground(new java.awt.Color(24, 32, 38));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        next2.setBackground(new java.awt.Color(24, 32, 38));
        next2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next2.setForeground(new java.awt.Color(255, 255, 255));
        next2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon/icons8-logout-rounded-left-25.png"))); // NOI18N
        next2.setText("Logout");
        next2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(next2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(next2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 620, 90, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HDUser.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        tblPost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPost);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        next.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next >");
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, 70, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("< Back");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 80, -1));

        Id.setText("jTextField1");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        Id1.setText("jTextField1");
        getContentPane().add(Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        Id3.setText("jTextField1");
        Id3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id3ActionPerformed(evt);
            }
        });
        getContentPane().add(Id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Id2.setText("jTextField1");
        getContentPane().add(Id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        Id4.setText("jTextField1");
        Id4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id4ActionPerformed(evt);
            }
        });
        getContentPane().add(Id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Id5.setText("jTextField1");
        Id5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id5ActionPerformed(evt);
            }
        });
        getContentPane().add(Id5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Id6.setText("jTextField1");
        Id6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id6ActionPerformed(evt);
            }
        });
        getContentPane().add(Id6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Id7.setText("jTextField1");
        Id7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id7ActionPerformed(evt);
            }
        });
        getContentPane().add(Id7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Id8.setText("jTextField1");
        Id8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id8ActionPerformed(evt);
            }
        });
        getContentPane().add(Id8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Id9.setText("jTextField1");
        Id9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id9ActionPerformed(evt);
            }
        });
        getContentPane().add(Id9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        Id10.setText("jTextField1");
        Id10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id10ActionPerformed(evt);
            }
        });
        getContentPane().add(Id10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void KlikTemukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikTemukanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_KlikTemukanMouseClicked

    private void KlikListPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikListPMouseClicked
     new ListPekerjaan().show();
      this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_KlikListPMouseClicked

    private void KlikCatatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikCatatanMouseClicked
    new Catatan().show();
      this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_KlikCatatanMouseClicked

    private void KlikEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KlikEditMouseClicked
      new EditAkunUser().show();
      this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_KlikEditMouseClicked

    private void Id3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id3ActionPerformed

    private void Id4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id4ActionPerformed

    private void TambahKeLiist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist1ActionPerformed
        dataposcontrol.DataList(Integer.parseInt(Id1.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }
    }//GEN-LAST:event_TambahKeLiist1ActionPerformed

    private void TambahKeLiist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist3ActionPerformed
        dataposcontrol.DataList(Integer.parseInt(Id3.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }          // TODO add your handling code here:
    }//GEN-LAST:event_TambahKeLiist3ActionPerformed

    private void TambahKeLiist4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist4ActionPerformed
        dataposcontrol.DataList(Integer.parseInt(Id4.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }            // TODO add your handling code here:
    }//GEN-LAST:event_TambahKeLiist4ActionPerformed

    private void TambahKeLiist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist2ActionPerformed
        dataposcontrol.DataList(Integer.parseInt(Id2.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }
    }//GEN-LAST:event_TambahKeLiist2ActionPerformed

    private void TambahKeLiist5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist5ActionPerformed
             dataposcontrol.DataList(Integer.parseInt(Id5.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }
    }//GEN-LAST:event_TambahKeLiist5ActionPerformed

    private void TambahKeLiist6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist6ActionPerformed
      dataposcontrol.DataList(Integer.parseInt(Id6.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }
    }//GEN-LAST:event_TambahKeLiist6ActionPerformed

    private void TambahKeLiist7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist7ActionPerformed
        dataposcontrol.DataList(Integer.parseInt(Id7.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }
    }//GEN-LAST:event_TambahKeLiist7ActionPerformed

    private void TambahKeLiist8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist8ActionPerformed
            dataposcontrol.DataList(Integer.parseInt(Id8.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }
    }//GEN-LAST:event_TambahKeLiist8ActionPerformed

    private void TambahKeLiist9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahKeLiist9ActionPerformed
          dataposcontrol.DataList(Integer.parseInt(Id9.getText()));
        boolean hasil = dataposcontrol.insertList();
        if (hasil){
            JOptionPane.showMessageDialog(null, "Pekerjaan Berhasil dimasukkan ke list");
            Temukan home = new Temukan();
            home.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Catatan Gagal Dihapus");
        }
    }//GEN-LAST:event_TambahKeLiist9ActionPerformed

    private void Id5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id5ActionPerformed

    private void Id6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id6ActionPerformed

    private void Id7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id7ActionPerformed

    private void Id8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id8ActionPerformed

    private void Id9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id9ActionPerformed

    private void Id10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id10ActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
       new Login().show();
this.dispose(); 
    }//GEN-LAST:event_jPanel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat1;
    private javax.swing.JLabel Alamat2;
    private javax.swing.JLabel Alamat3;
    private javax.swing.JLabel Alamat4;
    private javax.swing.JLabel Alamat5;
    private javax.swing.JLabel Alamat6;
    private javax.swing.JLabel Alamat7;
    private javax.swing.JLabel Alamat8;
    private javax.swing.JLabel Alamat9;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Deskripsi1;
    private javax.swing.JLabel Deskripsi2;
    private javax.swing.JLabel Deskripsi3;
    private javax.swing.JLabel Deskripsi4;
    private javax.swing.JLabel Deskripsi5;
    private javax.swing.JLabel Deskripsi6;
    private javax.swing.JLabel Deskripsi7;
    private javax.swing.JLabel Deskripsi8;
    private javax.swing.JLabel Deskripsi9;
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel Email2;
    private javax.swing.JLabel Email3;
    private javax.swing.JLabel Email4;
    private javax.swing.JLabel Email5;
    private javax.swing.JLabel Email6;
    private javax.swing.JLabel Email7;
    private javax.swing.JLabel Email8;
    private javax.swing.JLabel Email9;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Id1;
    private javax.swing.JTextField Id10;
    private javax.swing.JTextField Id2;
    private javax.swing.JTextField Id3;
    private javax.swing.JTextField Id4;
    private javax.swing.JTextField Id5;
    private javax.swing.JTextField Id6;
    private javax.swing.JTextField Id7;
    private javax.swing.JTextField Id8;
    private javax.swing.JTextField Id9;
    private javax.swing.JLabel JudulPekerjaan1;
    private javax.swing.JLabel JudulPekerjaan2;
    private javax.swing.JLabel JudulPekerjaan3;
    private javax.swing.JLabel JudulPekerjaan4;
    private javax.swing.JLabel JudulPekerjaan5;
    private javax.swing.JLabel JudulPekerjaan6;
    private javax.swing.JLabel JudulPekerjaan7;
    private javax.swing.JLabel JudulPekerjaan8;
    private javax.swing.JLabel JudulPekerjaan9;
    private javax.swing.JLabel KlikCatatan;
    private javax.swing.JLabel KlikEdit;
    private javax.swing.JLabel KlikListP;
    private javax.swing.JLabel KlikTemukan;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JLabel Logo4;
    private javax.swing.JLabel Logo5;
    private javax.swing.JLabel Logo6;
    private javax.swing.JLabel Logo7;
    private javax.swing.JLabel Logo8;
    private javax.swing.JLabel Logo9;
    private javax.swing.JLabel NamaPerusahaan1;
    private javax.swing.JLabel NamaPerusahaan2;
    private javax.swing.JLabel NamaPerusahaan3;
    private javax.swing.JLabel NamaPerusahaan4;
    private javax.swing.JLabel NamaPerusahaan5;
    private javax.swing.JLabel NamaPerusahaan6;
    private javax.swing.JLabel NamaPerusahaan7;
    private javax.swing.JLabel NamaPerusahaan8;
    private javax.swing.JLabel NamaPerusahaan9;
    private javax.swing.JLabel Pays1;
    private javax.swing.JLabel Pays2;
    private javax.swing.JLabel Pays3;
    private javax.swing.JLabel Pays4;
    private javax.swing.JLabel Pays5;
    private javax.swing.JLabel Pays6;
    private javax.swing.JLabel Pays7;
    private javax.swing.JLabel Pays8;
    private javax.swing.JLabel Pays9;
    private javax.swing.JButton TambahKeLiist1;
    private javax.swing.JButton TambahKeLiist2;
    private javax.swing.JButton TambahKeLiist3;
    private javax.swing.JButton TambahKeLiist4;
    private javax.swing.JButton TambahKeLiist5;
    private javax.swing.JButton TambahKeLiist6;
    private javax.swing.JButton TambahKeLiist7;
    private javax.swing.JButton TambahKeLiist8;
    private javax.swing.JButton TambahKeLiist9;
    private javax.swing.JLabel back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel l27;
    private javax.swing.JLabel l28;
    private javax.swing.JLabel l29;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l30;
    private javax.swing.JLabel l31;
    private javax.swing.JLabel l32;
    private javax.swing.JLabel l33;
    private javax.swing.JLabel l34;
    private javax.swing.JLabel l35;
    private javax.swing.JLabel l36;
    private javax.swing.JLabel l37;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel member;
    private javax.swing.JLabel next;
    private javax.swing.JLabel next1;
    private javax.swing.JLabel next2;
    private javax.swing.JLabel next3;
    private javax.swing.JLabel next4;
    private javax.swing.JLabel next5;
    private javax.swing.JTable tblPost;
    // End of variables declaration//GEN-END:variables

    
    
    public void aturButton(){
        if (noPost <= 9){
        back.setVisible(false);
        }else if (noPost > 9){
     back.setVisible(true);
    }
        if (noPost > jumlah ){
        next.setVisible(true);
        }else {
        next.setVisible(false);
        }
    }
    
    public void tampilData(int index,JLabel JudulPekerjaan, JLabel Deskripsi, JLabel NamaPerusahaan, JLabel Alamat,String nama, JLabel logo,JTextField Id ,JLabel Pays, JLabel Email
    ){
        JudulPekerjaan.setText(dtm.getValueAt(index, 0).toString());
        Deskripsi.setText(dtm.getValueAt(index, 1).toString());
        NamaPerusahaan.setText(dtm.getValueAt(index, 2).toString());
        Alamat.setText(dtm.getValueAt(index, 3).toString());
        Id.setText(dtm.getValueAt(index, 5).toString());
        Pays.setText(dtm.getValueAt(index,6).toString());
        Email.setText(dtm.getValueAt(index,7).toString());
        Toolkit tool = Toolkit.getDefaultToolkit();
        path = "src/image/";
        Image img = tool.getImage(path + nama);
        Image imagedResized=img.getScaledInstance (logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(imagedResized);
        logo.setIcon(imageIcon);
    }
    
     public void postKosong(JLabel JudulPekerjaan, JLabel Deskripsi, JLabel NamaPerusahaan, JLabel Alamat,JLabel logo,JTextField Id ,JLabel Pays, JLabel Email
    ){
        JudulPekerjaan.setText("");
        Deskripsi.setText("");
        NamaPerusahaan.setText("");
        Alamat.setText("");
        Id.setText("");
        Pays.setText("");
        Email.setText("");
        
        Toolkit tool = Toolkit.getDefaultToolkit();
        path = "src/image/";
        Image img = tool.getImage(path + "NO foto");
        Image imagedResized=img.getScaledInstance (logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon=new    ImageIcon(imagedResized);
        logo.setIcon(imageIcon);
    }
    
     public void tampilPost(){
         dtm = (DefaultTableModel) tblPost.getModel();
         dtm.setRowCount(0);
         listdata = dataposcontrol.DataPost();
         for (DataPosting data : listdata){
             dtm.addRow(new Object[]{
             
             data.getDataJudulPosting(),
             data.getDatadeskripsi(),
             data.getDatanamaperusahaan(),
             data.getDatalocation(),
             data.getDatagambar(),
             data.getDataid_posting(),
             data.getDatapays(),
             data.getDataemail(),
             });
            } 
          jumlah = dtm.getRowCount();
      
            // 1
           if (noPost<jumlah)  {
           tampilData(noPost, JudulPekerjaan1, Deskripsi1,NamaPerusahaan1,Alamat1,
                (String) dtm.getValueAt(noPost,4),Logo1,Id1,Pays1,Email1);
           } else{
           postKosong( JudulPekerjaan1, Deskripsi1,NamaPerusahaan1,Alamat1,
             Logo1,Id1,Pays1,Email1);
           }    
           //2
           if (noPost+1<jumlah)  {
           tampilData(noPost+1, JudulPekerjaan2, Deskripsi2,NamaPerusahaan2,Alamat2,
                (String) dtm.getValueAt(noPost+1,4),Logo2,Id2,Pays2,Email2);
           } else{
            postKosong( JudulPekerjaan2, Deskripsi2,NamaPerusahaan2,Alamat2,
             Logo2,Id2,Pays2,Email2);
           }
           // 3
           if (noPost+2<jumlah)  {
           tampilData(noPost+2, JudulPekerjaan3, Deskripsi3,NamaPerusahaan3,Alamat3,
                (String) dtm.getValueAt(noPost+2,4),Logo3,Id3,Pays3,Email3);
           } else{
            postKosong( JudulPekerjaan3, Deskripsi3,NamaPerusahaan3,Alamat3,
             Logo3,Id3,Pays3,Email3);
           }
          // 4
            if (noPost+3<jumlah)  {
           tampilData(noPost+3, JudulPekerjaan4, Deskripsi4,NamaPerusahaan4,Alamat4,
                (String) dtm.getValueAt(noPost+3,4),Logo4,Id4,Pays4,Email4);
           } else{
            postKosong( JudulPekerjaan4, Deskripsi4,NamaPerusahaan4,Alamat4,
             Logo4,Id4,Pays4,Email4);
           }
           //5
             if (noPost+4<jumlah)  {
           tampilData(noPost+4, JudulPekerjaan5, Deskripsi5,NamaPerusahaan5,Alamat5,
                (String) dtm.getValueAt(noPost+4,4),Logo5,Id5,Pays5,Email5);
           } else{
            postKosong( JudulPekerjaan5, Deskripsi5,NamaPerusahaan5,Alamat5,
             Logo5,Id5,Pays5,Email5);
           }
            
           //6
               if (noPost+5<jumlah)  {
           tampilData(noPost+5, JudulPekerjaan6, Deskripsi6,NamaPerusahaan6,Alamat6,
                (String) dtm.getValueAt(noPost+5,4),Logo6,Id6,Pays6,Email6);
           } else{
            postKosong( JudulPekerjaan6, Deskripsi6,NamaPerusahaan6,Alamat6,
             Logo6,Id6,Pays6,Email6);
           }
           //7
                  if (noPost+6<jumlah)  {
           tampilData(noPost+6, JudulPekerjaan7, Deskripsi7,NamaPerusahaan7,Alamat7,
                (String) dtm.getValueAt(noPost+6,4),Logo7,Id7,Pays7,Email7);
           } else{
            postKosong( JudulPekerjaan7, Deskripsi7,NamaPerusahaan7,Alamat7,
             Logo7,Id7,Pays7,Email7);
           }
           //8
           if (noPost+7<jumlah)  {
           tampilData(noPost+7, JudulPekerjaan8, Deskripsi8,NamaPerusahaan8,Alamat8,
                (String) dtm.getValueAt(noPost+7,4),Logo8,Id8,Pays8,Email8);
           } else{
            postKosong( JudulPekerjaan8, Deskripsi8,NamaPerusahaan8,Alamat8,
             Logo8,Id8,Pays8,Email8);
           }
           //9
             if (noPost+8<jumlah)  {
           tampilData(noPost+8, JudulPekerjaan9, Deskripsi9,NamaPerusahaan9,Alamat9,
                (String) dtm.getValueAt(noPost+8,4),Logo9,Id9,Pays9,Email9);
           } else{
            postKosong( JudulPekerjaan9, Deskripsi9,NamaPerusahaan9,Alamat9,
             Logo9,Id9,Pays9,Email9);
             }
           //10
            
           

    
      
           }
    
}